[build]
  base = "frontend"
  publish = "build"
  command = "yarn build"

# Optional: You can set environment variables here or via Netlify UI
# [build.environment]
#   REACT_APP_BACKEND_URL = "https://your-backend.example.com"

# Ensure SPA routing works (React Router fallback)
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  # Let API calls pass through untouched (useful if proxied via Netlify in future)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200