[build]
  base = "frontend"
  publish = "build"
  command = "yarn build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Proxy API requests to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback for React Router (must remain last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to mitigate browser cache issues and stale HTTP/3 Alt-Svc state
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/*"
  [headers.values]
    Alt-Svc = "clear"